In [1]:
%pip install numpy

Requirement already satisfied: numpy in .\codeit\Lib\site-packages (2.4.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
print(np.__version__)

2.4.2

In [4]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in .\codeit\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\codeit\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\codeit\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\codeit\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 1.1 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.7 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.7 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.7 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.7 MB 1.0 MB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.7 MB 997.5 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.7 MB 1.0 MB/s eta 0:00:08
   ------- -------------------------------- 1.8/9.7 MB 1.0 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.7 MB 971.0 kB/s eta 0:00:08
   --------- ------------------------------ 2.4/9.7 MB 995.5 kB/s eta 0:00:08
   --------- ------------------------------ 2.4/9.7 MB 995.5 kB/s eta 0:00:08
   --------- ------------------------------ 2.4/9.7 MB 995.5 kB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.7 MB 858.9 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.7 MB 893.9 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.7 MB 924.5 kB/s eta 0:00:08
   ------------- -------------------------- 3.4/9.7 MB 935.2 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.7 MB 967.5 kB/s eta 0:00:07
   ---------------- ----------------------- 3.9/9.7 MB 994.9 kB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.7 MB 998.9 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.7 MB 1.0 MB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.7 MB 1.0 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.7 MB 1.0 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.7 MB 1.0 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.7 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.7 MB 998.4 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.7 MB 998.4 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 1.0 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.7 MB 1.0 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.7 MB 961.9 kB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.7 MB 961.9 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.7 MB 949.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.7 MB 949.1 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.7 MB 934.1 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.7 MB 922.1 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.7 MB 922.1 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.7 MB 922.1 kB/s eta 0:00:04
   ----------------------------- ---------- 7.1/9.7 MB 895.0 kB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.7 MB 895.0 kB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.7 MB 895.0 kB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.7 MB 855.0 kB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.7 MB 855.0 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.7 MB 839.1 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.7 MB 844.6 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.7 MB 852.1 kB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.7 MB 852.1 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 867.7 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 867.7 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 862.7 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 866.8 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 866.8 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 871.3 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 871.7 kB/s  0:00:11
Installing collected packages: pandas
Successfully installed pandas-3.0.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np
import pandas as pd

In [ ]:
#Load Data

In [7]:
df = pd.read_csv('customer_purchase_data.csv')

In [8]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1500 non-null   int64
 1   Gender              1500 non-null   int64
 2   AnnualIncome        1500 non-null   float64
 3   NumberOfPurchases   1500 non-null   int64
 4   ProductCategory     1500 non-null   int64
 5   TimeSpentOnWebsite  1500 non-null   float64
 6   LoyaltyProgram      1500 non-null   int64
 7   DiscountsAvailed    1500 non-null   int64
 8   PurchaseStatus      1500 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 105.6 KB
None

In [9]:
df.shape

(1500, 9)

In [16]:
df.head(5)

,age,gender,annualincome,numberofpurchases,productcategory,timespentonwebsite,loyaltyprogram,discountsavailed,purchasestatus
0,40,1,66120.26794,8,0,30.568601,0,5,1
1,20,1,23579.77358,4,2,38.240097,0,5,0
2,27,1,127821.30640,11,2,31.633212,1,0,1
3,24,1,137798.62310,19,3,46.167059,0,4,1
4,31,1,99300.96422,19,1,19.823592,0,0,1

In [17]:
df.tail(5)

,age,gender,annualincome,numberofpurchases,productcategory,timespentonwebsite,loyaltyprogram,discountsavailed,purchasestatus
1495,39,1,65048.14183,13,0,34.590743,0,5,1
1496,67,1,28775.33107,18,2,17.625707,0,1,1
1497,40,1,57363.24754,7,4,12.206033,0,0,0
1498,63,0,134021.77550,16,2,37.311634,1,0,1
1499,50,0,52625.66597,13,0,25.348017,1,4,1

In [18]:
df.describe()

,age,gender,annualincome,numberofpurchases,productcategory,timespentonwebsite,loyaltyprogram,discountsavailed,purchasestatus
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000
mean,44.298667,0.504667,84249.164339,10.420000,2.012667,30.469040,0.326667,2.555333,0.43200
std,15.537259,0.500145,37629.493078,5.887391,1.428005,16.984392,0.469151,1.705152,0.49552
min,18.000000,0.000000,20001.512520,0.000000,0.000000,1.037023,0.000000,0.000000,0.00000
25%,31.000000,0.000000,53028.979155,5.000000,1.000000,16.156700,0.000000,1.000000,0.00000
50%,45.000000,1.000000,83699.581475,11.000000,2.000000,30.939516,0.000000,3.000000,0.00000
75%,57.000000,1.000000,117167.772900,15.000000,3.000000,44.369863,1.000000,4.000000,1.00000
max,70.000000,1.000000,149785.176500,20.000000,4.000000,59.991105,1.000000,5.000000,1.00000

In [ ]:
## Count Missing Value

In [ ]:
## Count Missing Value

## Count Missing Value

In [10]:
#Checks if there are null values in the dataset in each columns
print(df.isnull().sum())

Age                   0
Gender                0
AnnualIncome          0
NumberOfPurchases     0
ProductCategory       0
TimeSpentOnWebsite    0
LoyaltyProgram        0
DiscountsAvailed      0
PurchaseStatus        0
dtype: int64

## Find Duplicate Value

In [11]:
print("Duplicate rows found:", df.duplicated().sum())

Duplicate rows found: 112

## Standarized column Name

In [12]:
df.columns = [col.strip().upper() for col in df.columns]

In [13]:
df.columns

Index(['AGE', 'GENDER', 'ANNUALINCOME', 'NUMBEROFPURCHASES', 'PRODUCTCATEGORY',
       'TIMESPENTONWEBSITE', 'LOYALTYPROGRAM', 'DISCOUNTSAVAILED',
       'PURCHASESTATUS'],
      dtype='str')